[package]
name = "lix"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.26", features = ["derive"] }
serde = { version = "1.0.147", features = ["derive"] }
reqwest = { version = "0.11.13", features = ["json"] }
tokio = { version = "1.22.0", features = ["full"] }
serde_json = "1.0.88"
version-compare = "0.1.1"
futures = "0.3.25"
dialoguer = "^0.10.2"
tabled = { version = "*", features = ["color"] }
owo-colors = "3.5.0"

