[package]
name = "lix"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.20", features = ["derive"] }
serde = { version = "1.0.144", features = ["derive"] }
reqwest = { version = "0.11.11", features = ["json"] }
tokio = { version = "1.21.0", features = ["full"] }
indicatif = "0.17.0"
serde_json = "1.0.85"
version-compare = "0.1"
futures = "0.3.24"
prettytable-rs = "^0.9"

